### ISSUE TITLE
Mint ERROR: parameters 

### ISSUE THREAD

**Issue by colorstheforce** [The-Stripes-NFT/the-stripes-nft-contract#10]
Ive got it on Gitpod can Launch Server, Page Loads, WEb3 Connects, Reads mint/Maxmint from contract, But, When i hit Mint it errors  with Parameters 2 but got 1 
with researching forums ive found that the soulution is that i need to add my URI call function, i just dont know where i do that,
![ezgif com-gif-maker](https://user-images.githubusercontent.com/66538158/160850507-b6946981-aacc-4daf-b874-e7e0825003c7.gif)

**Comment by Cronosnauts** [comment]
same

**Comment by alisolanki** [comment]
If you check the contract out, the mint function on line 36 (https://github.com/The-Stripes-NFT/the-stripes-nft-contract/blob/main/TheStripesNFT.sol) takes 2 parameters. The address _to and uint256 _mintAmount.

This is perfectly fine. I think you have changed something in the minting site side of things nothing to do with the smart contracts.
